import { useEffect, useState } from 'react'
import './App.css'

const phone = '(540) 424-1852'
const secondaryPhone = '(202) 361-6799'
const email = 'info@malydiahealth.com'
const tel = phone.replace(/[^\d]/g, '')
const secondaryTel = secondaryPhone.replace(/[^\d]/g, '')
const services = [
  ['01', 'Medical Appointments', "Dependable transportation to and from doctors' offices, clinics, and healthcare facilities."],
  ['02', 'Dialysis Transportation', 'Reliable recurring transportation for patients attending dialysis appointments.'],
  ['03', 'Hospital & Outpatient', 'Transportation for eligible non-emergency hospital visits, outpatient procedures, and discharges.'],
  ['04', 'Rehabilitation & Therapy', 'Transportation to physical therapy, occupational therapy, rehabilitation, and follow-up appointments.'],
  ['05', 'Senior Transportation', 'Compassionate transportation designed around the needs of older adults.'],
  ['06', 'Private-Pay Transportation', 'Convenient transportation options for individuals and families arranging rides directly.'],
]
const values = [['✦', 'Compassionate Service'], ['↗', 'Dependable Transportation'], ['⌁', 'Safety-Focused'], ['◌', 'Professional Drivers'], ['□', 'Comfortable Rides'], ['♡', 'Personalized Assistance']]

function Logo({ light = false }) { return <a className={`logo ${light ? 'logo-light' : ''}`} href="/" aria-label="Malydia home"><img className="logo-image" src="/ChatGPT%20Image%20Sep%209,%202026,%2012_15_43%20PM.png" alt="Malydia Healthcare Transportation logo" /></a> }
function Button({ href, children, secondary = false }) { return <a className={`button ${secondary ? 'secondary' : ''}`} href={href}>{children}<span>↗</span></a> }
function Header({ open, setOpen }) {
  const links = [['/', 'Home'], ['/about', 'About Us'], ['/services', 'Services'], ['/service-area', 'Service Area'], ['/book-a-ride', 'Book a Ride'], ['/contact', 'Contact']]
  return <header className="site-header"><div className="header-inner"><Logo /><button className="menu-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle menu"><span /><span /></button><nav className={open ? 'open' : ''}>{links.map(([href, label]) => <a href={href} key={href} onClick={() => setOpen(false)}>{label}</a>)}</nav><div className="header-actions"><a className="call-link" href={`tel:${tel}`}>Call Us</a><Button href="/book-a-ride">Book a Ride</Button></div></div></header>
}
function Footer() { return <footer className="site-footer"><div className="footer-grid"><div><Logo light /><p className="footer-tag">Safe Rides. Healthier Tomorrows.</p></div><div><p className="footer-label">Explore</p><div className="footer-links"><a href="/">Home</a><a href="/about">About</a><a href="/services">Services</a><a href="/book-a-ride">Book a Ride</a><a href="/contact">Contact</a></div></div><div><p className="footer-label">Reach us</p><a href={`tel:${tel}`}>{phone}</a><a href={`tel:${secondaryTel}`}>{secondaryPhone}</a><a href={`mailto:${email}`}>{email}</a><span>Spotsylvania, Virginia</span></div></div><div className="footer-bottom"><span>© 2026 Malydia Healthcare Transportation LLC. All rights reserved.</span><span><a href="/privacy-policy">Privacy Policy</a><a href="/terms">Terms</a></span></div></footer> }
function Intro({ eyebrow, title, copy }) { return <section className="page-intro"><div className="container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="intro-copy">{copy}</p></div></section> }
function Heading({ eyebrow, title, copy }) { return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p>{copy}</p>}</div> }
function Cta() { return <section className="cta"><div className="container cta-grid"><div><p className="eyebrow light">Let’s get you there</p><h2>Ready when<br /><em>you are.</em></h2></div><div><p>Tell us where and when transportation is needed. Our team will review the details and follow up to confirm availability.</p><Button href="/book-a-ride">Request a ride</Button></div></div></section> }

function Home() { return <main><section className="hero"><div className="hero-image" /><div className="hero-shade" /><div className="container hero-content"><p className="eyebrow light">NEMT in Fredericksburg, Virginia</p><h1>Safe rides.<br /><em>Healthier tomorrows.</em></h1><p>Reliable, compassionate non-emergency medical transportation for patients, seniors, individuals with disabilities, and families throughout the Fredericksburg region.</p><div className="hero-actions"><Button href="/book-a-ride">Book Your Ride</Button><Button href={`tel:${tel}`} secondary>Call Us</Button></div><div className="trust">Safe <i /> Reliable <i /> Compassionate</div></div></section><section className="intro-band"><div className="container intro-grid"><div><p className="eyebrow">A better way to get there</p><h2>Care begins<br /><em>before arrival.</em></h2></div><p>Getting to an important appointment should feel simple. Malydia provides a thoughtful, dependable way for our neighbors to reach the care they need, with dignity at every step.</p><a className="text-link" href="/about">Meet Malydia ↗</a></div></section><section className="section"><div className="container"><Heading eyebrow="Our services" title="Transportation for the moments that matter." copy="From routine appointments to ongoing care, we help make each trip feel more manageable." /><div className="service-grid">{services.slice(0, 3).map(([n, title, copy]) => <a className="service-card" href="/services" key={title}><span className="number">{n}</span><h3>{title}</h3><p>{copy}</p><b>↗</b></a>)}</div><div className="center-link"><a className="text-link" href="/services">View all services ↗</a></div></div></section><section className="section why"><div className="container split"><div className="why-image" /><div><Heading eyebrow="Why Malydia" title="Transportation you can depend on." copy="Malydia Healthcare Transportation LLC was created to make transportation to important healthcare appointments easier, safer, and less stressful." /><div className="mini-values"><div><b>01</b> Respectful, passenger-centered service</div><div><b>02</b> Clear communication from request to arrival</div><div><b>03</b> A calmer way to move through the day</div></div><Button href="/about" secondary>Why choose us</Button></div></div></section><Cta /></main> }
function About() { return <><Intro eyebrow="About Malydia" title={<>Care in motion.<br /><em>People at the center.</em></>} copy="Malydia Healthcare Transportation LLC is a locally based transportation company focused on helping people reach healthcare appointments safely, comfortably, and on time." /><main><section className="section"><div className="container about-grid"><div><p className="eyebrow">Our approach</p><h2>Every passenger deserves to feel seen, heard, and supported.</h2></div><div className="prose"><p>We believe transportation is part of the care experience. That is why we focus on dignity, reliability, respect, communication, and passenger-centered service in every interaction.</p><p>Whether a ride is occasional or part of an ongoing routine, our goal is to make the journey feel clear and comfortable for individuals, families, seniors, and people living with disabilities.</p></div></div></section><section className="section white"><div className="container"><Heading eyebrow="What guides us" title="A steady presence for the road ahead." /><div className="values-grid">{values.map(([icon, title]) => <div className="value-card" key={title}><span>{icon}</span><h3>{title}</h3><p>Thoughtful support, clear communication, and respect in every interaction.</p></div>)}</div></div></section><Cta /></main></> }
function Services() { return <><Intro eyebrow="Our services" title={<>Transportation that<br /><em>fits your care.</em></>} copy="Reliable non-emergency medical transportation for important appointments, recurring care, and the people who help make it happen." /><main><section className="section"><div className="container service-list">{services.map(([n, title, copy]) => <article className="service-row" key={title}><span className="number">{n}</span><div><h2>{title}</h2><p>{copy}</p></div><a className="round-arrow" href="/book-a-ride">↗</a></article>)}</div></section><Cta /></main></> }
function Area() { return <><Intro eyebrow="Service area" title={<>Close to home.<br /><em>Here to help.</em></>} copy="We proudly serve patients and families across the Fredericksburg region and surrounding communities." /><main><section className="section white"><div className="container area-grid"><div className="map"><span>✦</span><b>Fredericksburg region</b></div><div><Heading eyebrow="Where we go" title="Serving our Virginia neighbors." copy="Our initial service area includes:" /><div className="area-list"><div><span>01</span><b>Fredericksburg</b></div><div><span>02</span><b>Spotsylvania County</b></div><div><span>03</span><b>Stafford County</b></div></div><p className="small-copy">Contact us to ask about transportation outside our primary service area.</p><Button href="/contact">Contact our team</Button></div></div></section><Cta /></main></> }
function RideForm() { const [sent, setSent] = useState(false); if (sent) return <div className="success"><span>✓</span><h2>Thank you for reaching out.</h2><p>Your request has been received. Our team will contact you to confirm availability and trip details.</p><button className="text-link" onClick={() => setSent(false)}>Submit another request ↗</button></div>; return <form className="ride-form" onSubmit={(e) => { e.preventDefault(); setSent(true) }}><div className="form-row"><label>First Name<input required /></label><label>Last Name<input required /></label></div><div className="form-row"><label>Phone Number<input required type="tel" /></label><label>Email<input type="email" /></label></div><label>Pickup Address<input required placeholder="Street, city, state" /></label><label>Destination<input required placeholder="Facility or destination address" /></label><div className="form-row"><label>Appointment Date<input required type="date" /></label><label>Appointment Time<input required type="time" /></label></div><fieldset><legend>Return ride needed?</legend><label><input type="radio" name="return" defaultChecked /> Yes</label><label><input type="radio" name="return" /> No</label></fieldset><label>Passenger mobility needs<input placeholder="Please share only what helps us plan the ride" /></label><label>Additional information<textarea rows="4" placeholder="Anything else we should know about the trip?" /></label><p className="notice">Submitting a ride request does not guarantee transportation. Our team will contact you to confirm availability and trip details.</p><button className="button" type="submit">Submit ride request ↗</button></form> }
function Book() { return <><Intro eyebrow="Book a ride" title={<>Let’s make your<br /><em>next trip easier.</em></>} copy="Share a few trip details below. Our team will review your request and contact you to confirm availability." /><main><section className="section white"><div className="container booking-grid"><div><Heading eyebrow="Ride request" title="A simple first step." copy="Please do not include detailed medical diagnoses or other sensitive health information in this form." /><div className="booking-contact"><p className="eyebrow">Prefer to talk?</p><a href={`tel:${tel}`}>{phone}</a><a href={`tel:${secondaryTel}`}>{secondaryPhone}</a><a href={`mailto:${email}`}>{email}</a></div></div><RideForm /></div></section></main></> }
function Contact() { return <><Intro eyebrow="Contact" title={<>We’re here to<br /><em>help you get there.</em></>} copy="Have a question about a trip or our service area? Reach out and our team will be glad to connect." /><main><section className="section white"><div className="container contact-grid"><div><p className="eyebrow">Malydia Healthcare Transportation LLC</p><h2>Let’s talk about your transportation needs.</h2><div className="contact-detail"><span>Call</span><div><a href={`tel:${tel}`}>{phone}</a><br /><a href={`tel:${secondaryTel}`}>{secondaryPhone}</a></div></div><div className="contact-detail"><span>Email</span><a href={`mailto:${email}`}>{email}</a></div><div className="contact-detail"><span>Located in</span><span>Spotsylvania, Virginia</span></div></div><div className="contact-image" /></div></section></main></> }
function Legal({ terms = false }) { return <><Intro eyebrow={terms ? 'Terms & conditions' : 'Privacy policy'} title={terms ? <>Clear expectations.<br /><em>Respectful service.</em></> : <>Your privacy<br /><em>matters to us.</em></>} copy={terms ? 'A plain-language overview of using this website and requesting transportation.' : 'How Malydia Healthcare Transportation LLC handles information shared through this website.'} /><main><section className="section white"><div className="container legal"><p><strong>Last updated: September 2026</strong></p><h2>{terms ? 'Using this website' : 'Information we collect'}</h2><p>{terms ? 'This website shares information about Malydia Healthcare Transportation LLC and receives general ride requests. Content is informational and does not create a transportation agreement until our team confirms availability and trip details.' : 'When you contact us or submit a ride request, we may receive the information you choose to provide, such as your name, contact details, trip addresses, appointment timing, and mobility notes.'}</p><h2>{terms ? 'Ride requests' : 'How we use information'}</h2><p>We use submitted information to respond to inquiries, review transportation requests, coordinate communication, and improve the clarity of our services. Please do not submit detailed medical diagnoses or unnecessary protected health information through the general website form.</p><h2>Questions</h2><p>Contact <a href={`mailto:${email}`}>{email}</a> or <a href={`tel:${tel}`}>{phone}</a>.</p></div></section></main></> }

function App() { const [open, setOpen] = useState(false); const [path, setPath] = useState(window.location.pathname); useEffect(() => { const pop = () => setPath(window.location.pathname); const click = (e) => { const a = e.target.closest('a'); if (a && a.origin === window.location.origin && !a.pathname.includes('.') && a.pathname !== window.location.pathname) { e.preventDefault(); history.pushState({}, '', a.pathname); setPath(a.pathname); setOpen(false); window.scrollTo(0, 0) } }; addEventListener('popstate', pop); document.addEventListener('click', click); return () => { removeEventListener('popstate', pop); document.removeEventListener('click', click) } }, []); const page = path === '/about' ? <About /> : path === '/services' ? <Services /> : path === '/service-area' ? <Area /> : path === '/book-a-ride' ? <Book /> : path === '/contact' ? <Contact /> : path === '/privacy-policy' ? <Legal /> : path === '/terms' ? <Legal terms /> : <Home />; return <><Header open={open} setOpen={setOpen} />{page}<Footer /></> }
export default App
